// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FROnV9-xzfVSCpNsn76TyHfjvY_0LDk',
    appId: '1:336675706450:web:b1e12b016b734e78efb18b',
    messagingSenderId: '336675706450',
    projectId: 'moneymanager-6d869',
    authDomain: 'moneymanager-6d869.firebaseapp.com',
    storageBucket: 'moneymanager-6d869.firebasestorage.app',
    measurementId: 'G-SVWD47TZXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDni3FteAun6c2HZFEIkAZlsq2BO3qrZPs',
    appId: '1:336675706450:android:26b42e44b5601d5befb18b',
    messagingSenderId: '336675706450',
    projectId: 'moneymanager-6d869',
    storageBucket: 'moneymanager-6d869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUeM1zWHv3tnd-f1HhOO5k-GEhls25oXE',
    appId: '1:336675706450:ios:c9640476476ee7bcefb18b',
    messagingSenderId: '336675706450',
    projectId: 'moneymanager-6d869',
    storageBucket: 'moneymanager-6d869.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProjectProvincevu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUeM1zWHv3tnd-f1HhOO5k-GEhls25oXE',
    appId: '1:336675706450:ios:c9640476476ee7bcefb18b',
    messagingSenderId: '336675706450',
    projectId: 'moneymanager-6d869',
    storageBucket: 'moneymanager-6d869.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProjectProvincevu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0FROnV9-xzfVSCpNsn76TyHfjvY_0LDk',
    appId: '1:336675706450:web:c890076306698f40efb18b',
    messagingSenderId: '336675706450',
    projectId: 'moneymanager-6d869',
    authDomain: 'moneymanager-6d869.firebaseapp.com',
    storageBucket: 'moneymanager-6d869.firebasestorage.app',
    measurementId: 'G-TVE73TG8R6',
  );
}
